# Generated by Django 4.0 on 2021-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createid',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=True)),
                ('namepc', models.CharField(max_length=100)),
                ('ubicationpc', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
